#include "./Header Files/init.h"

void init() {
    createDirectories("C:/ProgramData/WinShareLoc/languages/");
    JSONHandler handler("");

    std::map<std::string, std::variant<std::string, int>> en_EN = {
      {
        {"appName", "WinShareLoc"}, {"english", "English"}, {"languageInfoEnglish", "Set the language to English"}, {"romanian", "Romanian"}, {"languageInfoRomanian", "Set the language to Romanian"}, {"file", "File"}, {"help", "Help"},
        {"home", "Home"}, {"language", "Language"}, {"FILE_new_Connection", "New Connection"}, {"FILE_close_connection", "Close Connection"},{"FILE_configurations", "Configurations"}, {"FILE_load_config", "Load Configuration File"}, {"FILE_exit", "Exit"},
        {"FILE_STATUS_new_connection", "Initiate a new connection"}, {"FILE_STATUS_close_connection", "Close current connection"}, {"FILE_STATUS_configurations", "Open Configuration window"}, {"FILE_STATUS_load_config", "Load config file manually"},
        {"FILE_STATUS_exit", "Terminate the proccess of this application"}, {"HELP_instructions", "Instructions"}, {"HELP_help", "Help"}, {"HELP_github", "GitHub Repo"}, {"HELP_about", "About"}, {"HELP_STATUS_instructions", "Get instructions how to use this application"},
        {"HELP_STATUS_help", "Get informations about this program"}, {"HELP_STATUS_github", "Open the GitHub Repository for this app"}, {"HELP_STATUS_about", "Get a brief about this app"},
        {"HELP_instructions_text", "Step 1: Initiate a new Connection\\nStep 2: Select a file/folder\\nStep 3: Send\\nStep 4: Wait to complete\\nStep 5: Done!\\n\\nAll instructions can be found on GitHub Repo:"}, {"HELP_help_text", ""},
        {"HELP_about_aboutTitle", "About"}, {"HELP_about_aboutText", "        WinShareLoc is the result of my efforts within the bachelor's thesis project at the Faculty of Electronics, Telecommunications, and Information Technology at the Technical University of Cluj-Napoca. The project was conceived to provide an efficient and user-friendly solution for file exchange between computers connected to the same local network on the Windows platform.\\n\\nProject Goal:\\n        The main objective of the WinShareLoc project was to develop a software application that facilitates rapid and secure file transfer between devices on a local network. Leveraging the knowledge acquired during my studies and my skills in C++ programming and the use of the wxWidgets library for the graphical interface, I created an intuitive and efficient application."},
        {"HELP_about_authorsTitle", "Authors"}, {"HELP_about_authorsText", "Developer:\\n    AmicuLL:     The main developer of the WinShareLoc application and the author of this bachelor's thesis project. AmicuLL is responsible for the conception, implementation, and testing of the application, bringing it to life with passion and dedication.\\n\\nThesis Supervisor:\\n    L. B.:     The thesis supervisor of the WinShareLoc project. L. B. provided guidance and support throughout the development of this project, offering invaluable advice and feedback for its success."},
        {"HELP_about_licenseTitle", "License"}, {"HELP_about_licenseText", "Ce licență să aleg oare? GNU v3?"}, {"HELP_about_softwareUsedTitle", "Software Used"}, {"HELP_about_softwareUsedText", "\\n    C++: The primary programming language used for the development of the WinShareLoc application. C++ provided the foundation for implementing the core functionalities of the program.\\n\\n\\n\\n\\n    wxWidgets: A C++ library used for developing the graphical user interface (GUI) of the WinShareLoc application. wxWidgets facilitated the creation of an intuitive and user-friendly interface for interacting with the program."},
        {"HOME_button", "HOME"}, {"TRANSFER_button", "TRANSFER"}, {"CONFIGURATIONS_button", "CONFIGURATIONS"}, {"INFORMATIONS_button", "INFORMATIONS"},
        {"HOME_text", "        WinShareLoc is the ideal solution for fast and secure file exchange between computers on the local network. Whether you're working in a project team or simply want to share files between devices in the same location, WinShareLoc is the perfect tool for you.\\n\\n        How it works:\\n                1.Select files: Choose the files you want to send or receive.\\n                2.Connect to the network: WinShareLoc automatically identifies devices on the local network and allows you to quickly connect for file transfer.\\n                3.Secure transfer: Using TCP and UDP protocols, WinShareLoc ensures fast and secure file transfer between connected devices.\\n\\n        Key features:\\n\\t• Fast file transfer via TCP.\\n\\t• Efficient signaling via UDP for identifying devices on the local network.\\n\\t• User-friendly and easy-to-use graphical interface."},
        {"CONFIG_nickname", "Nickname"}, {"CONFIG_IPProtVer", "IP Protocol Version"}, {"CONFIG_saveDest", "Save Location"}, {"CONFIG_loadConfig", "Load Config"}, {"CONFIG_apply", "Apply"}, {"CONFIG_OK", "OK"}, {"CONFIG_saveConfig", "Save Config"}, {"CONFIG_cancel", "Cancel"},
        {"INFO_IPV4", "Your IPv4 IP:"}, {"INFO_IPV6", "Your IPv6 IP:"}, {"INFO_displayedName", "Your displayed name:"}, {"INFO_loadedConfig", "Loaded config:"}, {"INFO_connectedWith", "Connected with:"}, {"INFO_isNotConnected", "Not Connected"}, {"INFO_isConnected", "Connected"}, {"INFO_isNotTransfering", "Not Transfering"},
        {"INFO_isTransfering", "Transfering"}, {"INFO_isNotAvailable", "Not Available"}, {"INFO_isAvailable", "Available"}
      }
    };
    handler.writeJSON(en_EN, "C:/ProgramData/WinShareLoc/languages/en_EN.json");

    std::map<std::string, std::variant<std::string, int>> ro_RO = {
      {
        {"appName", "WinShareLoc"}, {"english", "Engleză"}, {"languageInfoEnglish", "Setetează limba aplicației în Engleză"}, {"romanian", "Română"}, {"languageInfoRomanian", "Setetează limba aplicației în Română"}, {"file", "Fișier"},
        {"help", "Ajutor"}, {"home", "Acasă"}, {"language", "Limbă"}, {"FILE_new_Connection", "Conexiune nouă"}, {"FILE_close_connection", "Închide conexiunea"}, {"FILE_configurations", "Configurații"}, {"FILE_load_config", "Încărcare fișier config"}, {"FILE_exit", "Închide aplicația"},
        {"FILE_STATUS_new_connection", "Inițiere conexiune nouă"}, {"FILE_STATUS_close_connection", "Închide conexiunea curentă"}, {"FILE_STATUS_configurations", "Deschide fereastra de configurare"}, {"FILE_STATUS_load_config", "Încărcare fișier de configurare manual"}, {"FILE_STATUS_exit", "Închide procesul aplicației"},
        {"HELP_instructions", "Instrucțiuni"}, {"HELP_help", "Ajutor"}, {"HELP_github", "Depozit GitHub"}, {"HELP_about", "Despre"}, {"HELP_STATUS_instructions", "Obține instrucțiuni despre cum să folosești aplicația"},
        {"HELP_STATUS_help", "Obține informații despre program"}, {"HELP_STATUS_github", "Deschide într-un browser depozitul pe GitHub al acestei aplicații"}, {"HELP_STATUS_about", "Obține detalii despre aplicație"},
        {"HELP_instructions_text", "Pasul 1: Inițiați o nouă conexiune\\nPasul 2: Selectați un fișier/dosar\\nPasul 3: Trimiteți\\nPasul 4: Așteptați finalizarea\nPasul 5: Gata!\\n\\nToate instrucțiunile pot fi găsite pe Repository-ul GitHub:"}, {"HELP_help_text", ""},
        {"HELP_about_aboutTitle", "Despre"}, {"HELP_about_aboutText", "        WinShareLoc este rezultatul eforturilor mele în cadrul proiectului tezei de licență la Facultatea de Electronică, Telecomunicații și Tehnologia Informației din cadrul Universității Tehnice din Cluj-Napoca. Proiectul a fost conceput pentru a oferi o soluție eficientă și ușor de utilizat pentru schimbul de fișiere între computere conectate la aceeași rețea locală pe platforma Windows.\\n\\nObiectivul proiectului:\\n        Obiectivul principal al proiectului WinShareLoc a fost dezvoltarea unei aplicații software care facilitează transferul rapid și sigur de fișiere între dispozitive dintr-o rețea locală. Folosind cunoștințele dobândite în timpul studiilor și abilitățile mele în programarea C++ și utilizarea bibliotecii wxWidgets pentru interfața grafică, am creat o aplicație intuitivă și eficientă."},
        {"HELP_about_authorsTitle", "Autori"}, {"HELP_about_authorsText", "Dezvoltator:\\n    AmicuLL:     Dezvoltatorul principal al aplicației WinShareLoc și autorul acestui proiect de teză de licență. AmicuLL este responsabil pentru conceperea, implementarea și testarea aplicației, dându-i viață cu pasiune și dăruire.\\n\\nCoordonator știinșific:\\n    Lucian Blaga:     Coordonator licență al proiectului WinShareLoc. L. B. a oferit îndrumări și sprijin pe parcursul dezvoltării acestui proiect, oferind sfaturi și feedback neprețuit pentru succesul acestuia."},
        {"HELP_about_licenseTitle", "Licență"}, {"HELP_about_licenseText", "Nu știu ce licență"}, {"HELP_about_softwareUsedTitle", "Software folosit"}, {"HELP_about_softwareUsedText", "\\n    C++: limbajul de programare principal utilizat pentru dezvoltarea aplicației WinShareLoc. C++ a oferit fundația pentru implementarea funcționalităților de bază ale programului.\\n\\n\\n\\n\\n    wxWidgets: O bibliotecă C++ utilizată pentru dezvoltarea interfeței grafice cu utilizatorul (GUI) a aplicației WinShareLoc. wxWidgets a facilitat crearea unei interfețe intuitive și ușor de utilizat pentru a interacționa cu programul."},
        {"HOME_button", "Acasă"}, {"TRANSFER_button", "Transferuri"}, {"CONFIGURATIONS_button", "Configurații"},
        {"INFORMATIONS_button", "Informații"}, {"HOME_text", "        WinShareLoc este soluția ideală pentru schimbul rapid și sigur de fișiere între computere din rețeaua locală. Indiferent dacă lucrați într-o echipă de proiect sau pur și simplu doriți să partajați fișiere între dispozitive din aceeași locație, WinShareLoc este instrumentul perfect pentru dvs.\\n\\n        Cum funcționează:\\n                1.Selectați fișierele: alegeți fișierele dorite pentru a trimite sau a primi.\\n                2.Conectați-vă la rețea: WinShareLoc identifică automat dispozitivele din rețeaua locală și vă permite să vă conectați rapid pentru transfer de fișiere.\\n                3.Transfer securizat: folosind protocoalele TCP și UDP, WinShareLoc asigură rapid și sigur transfer de fișiere între dispozitivele conectate.\\n\\n        Caracteristici cheie:\\n\\t• Transfer rapid de fișiere prin TCP.\\n\\t• Semnalizare eficientă prin UDP pentru identificarea dispozitivelor din rețeaua locală.\\n\\t• Ușor de utilizat și interfață grafică ușor de utilizat."},
        {"CONFIG_nickname", "Poreclă"}, {"CONFIG_IPProtVer", "Versiunea protocolului IP"}, {"CONFIG_saveDest", "Directorul salvare fișier"}, {"CONFIG_loadConfig", "Încarcă configurarea"}, {"CONFIG_apply", "Aplică"},
        {"CONFIG_OK", "OK"}, {"CONFIG_saveConfig", "Salvează"}, {"CONFIG_cancel", "Anulează"}, {"INFO_IPV4", "Adresa IPv4:"}, {"INFO_IPV6", "Adresa IPv6:"}, {"INFO_displayedName", "Numele tău afișat:"}, {"INFO_loadedConfig", "Config-ul folosit:"},
        {"INFO_connectedWith", "Conectat cu:"}, {"INFO_isNotConnected", "Fără conexiune"}, {"INFO_isConnected", "Conectat"}, {"INFO_isNotTransfering", "Nu se transferă"}, {"INFO_isTransfering", "Se transferă"}, {"INFO_isNotAvailable", "Nu ești disponibil"}, {"INFO_isAvailable", "Disponibil"}
      }
    };
    handler.writeJSON(ro_RO, "C:/ProgramData/WinShareLoc/languages/ro_RO.json");
    return;
    }